# Generated by Django 4.0.3 on 2022-04-21 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosplayers', '0003_cospblog_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cospblog',
            name='like',
            field=models.ManyToManyField(related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
