# Generated by Django 4.0.3 on 2022-04-22 00:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosplayers', '0004_cospblog_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='cospblog',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
