# Generated by Django 4.0.3 on 2022-04-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosplayers', '0005_cospblog_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cospblog',
            name='category',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
